### PR TITLE
Mobile highlighter

### LINKED ISSUE #314: highlighter covers menu in mobile
Image from iOS (2)

### PR DESCRIPTION
**Pull request by KutnerUri**
fix mobile highlighter hiding the header in mobile,
closed #314 

- move highlighter position to bottom in mobile
  - add our user agent provider
- exclude highlighter from banner

### CODE REVIEW

**Review by odedre — APPROVED** [review]

**Comment by KutnerUri** [comment]
I agree, we shouldn't add things to ui-foundation.

The highlighter was hiding items in mobile, so I wanted to move it to the bottom position.
I used our existing is-mobile hook that depend on the user agent context. We could also check directly from window, but that will not work in the future when using ssr

**Comment by KutnerUri** [comment]
@ranm8 I agree, we shouldn't add things to ui-foundation.

The highlighter was hiding items in mobile, so I wanted to move it to the bottom position.
I used our existing is-mobile hook that depend on the user agent context. We could also check directly from window, but that will not work in the future when using ssr

**Comment by ranm8** [comment]
what do you suggest for now?

**Comment by ranm8** [comment]
what do you suggest for now?

**Comment by KutnerUri** [comment]
@ranm8 - using it like so. Then User Agent will be available to whomever needs it, and we will be able to inject a virtual one from SSR in the future.

**Pull request merged**
