### PR TITLE
[EXPERIMENT] Imageless

### LINKED ISSUE #330: error "Maximum call stack size exceeded" during build in GH PRs
getting this error during the build step of the github "tests" action:
```
Maximum call stack size exceeded
```
as seen here - https://github.com/teambit/bit-dev/runs/5648548548?check_suite_focus=true

It is happening _consistently_ during the `teambit.preview/preview:GenerateEnvTemplate` step of the build, after loading the 3 envs of the project.

### PR DESCRIPTION
**Pull request by KutnerUri**
a branch of bit-dev without images. ~43MB less! 🥗 

related to #339 
it seems it did not fix #330, tests only pass 1/3 of runs

### CODE REVIEW

**Comment by ranm8** [comment]
i don't understand this pr

**Comment by KutnerUri** [comment]
this is an experiment to see if removing images from the source would fix the PR tests.
please ignore

**Comment by KutnerUri** [comment]
this is an experiment to see if removing images from the source would fix the PR tests.
@ranm8  please ignore

**Comment by KutnerUri** [comment]
stale

**Pull request closed without merging**
